<?php
/**
 * @file
 * This file is used to write hooks that used in the module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_form_alter().
 */
function nnd_manage_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#validate'][] = 'nn_manage_json_validate';
}

/**
 * Implements hook_form_alter().
 */
function nnd_manage_form_block_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['revision_information']['#access'] = FALSE;
  $form['#validate'][] = 'nn_manage_json_validate';
}

/**
 * Validate json format.
 * @param array $form
 * @param FormStateInterface $form_state
 */
function nnd_manage_json_validate(array &$form, FormStateInterface $form_state) {
  $entity = $form_state->getFormObject()->getEntity();
  foreach ($form_state->getValues() as $field => $value) {
    if ($entity->hasField($field) && $entity->get($field)->getFieldDefinition()->getType() == 'text_with_summary' && $entity->get('body')->getFieldDefinition()->getTargetBundle() == 'json') {
      foreach ($value as $item) {
        if (!empty($item['value']) && empty(Json::decode($item['value']))) {
          $form_state->setErrorByName($field, t('Invalid JSON format'));
        }
      }
    }
  }
}